FROM python:3.8-slim

WORKDIR /taski

COPY backend/ backend/

EXPOSE 8080 

RUN pip install --upgrade pip     
RUN pip install -r ./backend/requirements.txt
CMD ["python", "./backend/manage.py"]
