stages:
    - build
    - test
    - deploy

fetch_dependencies_job:
    stage: build
    image: python:3.8-slim
    script:
        - cd ./taski/backend
        - python manage.py
    allow_failure: true
    rules:
    - when: on_success
    
build_job:
    stage: build
    image: python:3.8-slim
    needs: 
        - fetch_dependencies_job
    script: 
        - cd ./taski/backend
        - python manage.py
    artifacts: 
        paths:
            - "./backend/build_release/"
    rules:
    - when: on_success
            
test_job:
    stage: test
    image: python:3.8-slim
    needs:
        - build_job
    script:
        - cd ./taski/backend
        - python manage.py
    artifacts:
        paths:
    rules:
    - when: on_success

deploy_job:
    stage: deploy
    script:
        - cd ./taski/backend
        - python manage.py
    only: 
        - backend_production

