name: Docker Image CI   

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t tasks2 ./taski/.
  update:
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
    - uses: actions/checkout@v4
    - name: Update to Docker Hub
      run: docker image push akaannak/tasks2
    
